# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "rust_sample"
version = "0.1.0"
edition = "2021"
include = [
    "/src",
]

[dependencies]
pyo3 = "0.18.2"

